### get all artefacts
GET http://localhost:8080/api/artefact


###
POST http://localhost:8080/api/museum/create
Content-Type: application/json

{
  "name": "Old Arts Building",
  "location": "Hatfield, Pretoria",
  "description": "The Old Arts Building was designed by the London-born architect, Piercy (Patrick) James Eagle (1875-1932).",
  "openingHours": [
    {
      "day": "Monday",
      "openingTime": "09:00",
      "closingTime": "17:00"
    }
  ],
  "imageUrl": "string"
}

### create an artefact
POST http://localhost:8080/api/artefact/create
Content-Type: application/json

{
  "title": "Potrait of an Old Man",
  "creator": "Vincent Van Gogh",
  "description": "string",
  "collectionName": "string",
  "museumName": "Old Arts Building",
  "dateCreated": "string",
  "locationCreated": "string",
  "physicalDimensions": "string",
  "type": "Portrait",
  "rights": " Van Gogh Museum, Amsterdam (Vincent van Gogh Foundation), Van Gogh Museum, Amsterdam (Vincent van Gogh Foundation)",
  "medium": "string"
}

### get all artefacts by categoryName
GET http://localhost:8080/api/artefact/collection/Portrait
