### get all artefacts
GET http://localhost:8080/api/artefact


### Create Musuem
POST http://localhost:8080/api/museum/create
Content-Type: application/json

{
  "name": "Old Arts Building",
  "location": "Hatfield, Pretoria",
  "description": "The Old Arts Building was designed by the London-born architect, Piercy (Patrick) James Eagle (1875-1932).",
  "openingHours": [
    {
      "day": "Monday",
      "openingTime": "09:00",
      "closingTime": "17:00"
    }
  ],
  "imageUrl": "string"
}

### create an artefact
POST http://localhost:8080/api/artefact/create
Content-Type: application/json

{
  "title": "Potrait of an Old Man",
  "creator": "Vincent Van Gogh",
  "description": "string",
  "collectionName": "string",
  "museumName": "Old Arts Building",
  "dateCreated": "string",
  "locationCreated": "string",
  "physicalDimensions": "string",
  "type": "Portrait",
  "rights": " Van Gogh Museum, Amsterdam (Vincent van Gogh Foundation), Van Gogh Museum, Amsterdam (Vincent van Gogh Foundation)",
  "medium": "string"
}

### get all artefacts by categoryName
GET http://localhost:8080/api/artefact/collection/Portrait


### Upload using @ModelAttribute
POST http://localhost:8080/api/artefact/create
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="title"

Potrait of an Old Man
--boundary123
Content-Disposition: form-data; name="creator"

Vincent Van Gogh
--boundary123
Content-Disposition: form-data; name="description"

A post-impressionist portrait
--boundary123
Content-Disposition: form-data; name="museumName"

Old Arts Building
--boundary123
Content-Disposition: form-data; name="dateCreated"

1889
--boundary123
Content-Disposition: form-data; name="locationCreated"

Saint-Rémy
--boundary123
Content-Disposition: form-data; name="physicalDimensions"

65x50 cm
--boundary123
Content-Disposition: form-data; name="type"

Portrait
--boundary123
Content-Disposition: form-data; name="rights"

Van Gogh Museum
--boundary123
Content-Disposition: form-data; name="medium"

Oil on canvas
--boundary123
Content-Disposition: form-data; name="imageFile"; filename="portrait.jpg"
Content-Type: image/jpeg

< ./portrait.jpg
--boundary123--

###
GET http://localhost:8080/api/museum/chat
Content-Type: application/json

{
  "question": "How do I use this app?"
}
