services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
    environment:
      - SERVICES=s3 # we only need s3 bucket
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data # we need this to make our volume work
      - DEFAULT_REGION=af-south-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    volumes:
      - "./localstack_data:/var/lib/localstack" # Mounts the local directory to the container
      - "/var/run/docker.sock:/var/run/docker.sock" # Mounts the docker socket
