spring:
  application:
    name: backend
  docker:
    compose:
      enabled: false
  profiles:
    active: ${spring.profiles.active:test}
  datasource:
    driver-class-name: org.postgresql.Driver


  
