spring:
  docker:
    compose:
      enabled: true
      file: "backend/compose.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/museum_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update