spring:
  datasource:
    url: jdbc:postgresql://artifactup.cpiogs86w7dt.af-south-1.rds.amazonaws.com:5432/museum_db
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  secret.key: ${AWS_SECRET_KEY}
  access.key: ${AWS_ACCESS_KEY}
  endpoint: https://s3.af-south-1.amazonaws.com

openai:
  secret.key: ${OPENAI_SECRET_KEY}
  endpoint: https://api.openai.com/v1/chat/completions
