spring:
  docker:
    compose:
      enabled: true
      file: "./backend/compose.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/museum_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
  secret.key: testkey
  access.key: testsecret
  endpoint: http://s3.localhost.localstack.cloud:4566
