spring:
  docker:
    compose:
      enabled: true
      file: "./compose_db.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/museum_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
  secret.key: testkey
  access.key: testsecret
# uncomment to use localstack instead
#   endpoint: http://s3.localhost.localstack.cloud:4566
#   s3:
#     bucket-name: museum-artefacts
# # ---
  endpoint: https://s3.af-south-1.amazonaws.com
  s3:
    bucket-name: museum-artefacts-aup
