spring:
  datasource:
    url: jdbc:postgresql://artifactup.czwyiwimints.af-south-1.rds.amazonaws.com:5432/museum_db
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  secret.key: ${AWS_SECRET_KEY}
  access.key: ${AWS_ACCESS_KEY}
  endpoint: https://s3.af-south-1.amazonaws.com
  s3:
    bucket-name: museum-artefacts-aup

spring.ai.openai.api-key: YOUR_OPENAI_API_KEY
