name: Main CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
#  backend-build:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: backend
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: maven
#
#      - name: Build Project
#        env:
#          AWS_DB_USER: ${{ secrets.AWS_DB_USER }}
#          AWS_DB_PASS: ${{ secrets.AWS_DB_PASS }}
#        run: mvn clean install -DskipTests
#
#      - name: Login to docker hub
#        run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }}
#      - name: Build docker image
#        run: docker build -t maverickgdn01/artifactup .
#      - name: Publish image to docker hub
#        run: docker push maverickgdn01/artifactup:latest

#  Build the frontend, React app and push to dockerhub
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }}
      - name: Build docker image
        run: docker build -t maverickgdn01/artifactup-frontend .
      - name: Publish image to docker hub
        run: docker push maverickgdn01/artifactup-frontend:latest



#  deploy-backend:
#    needs: backend-build
#    runs-on: [aws-ec2-backend]
#    steps:
#      - name: Verify Docker Installation
#        run: docker --version
#      - name: Pull Image from Docker Hub
#        run: docker pull maverickgdn01/artifactup:latest
#      - name: Delete Existing Container
#        run: docker rm -f artifactup
#      - name: Run Docker Container
#        run: |
#          docker run -d -p 8080:8080 --name artifactup \
#            -e AWS_DB_USER=${{ secrets.AWS_DB_USER }} \
#            -e AWS_DB_PASS=${{ secrets.AWS_DB_PASS }} \
#            maverickgdn01/artifactup:latest

  deploy-frontend:
    needs: frontend-build
    runs-on: [aws-ec2-backend]
    steps:
      - name: Verify Docker Installation
        run: docker --version
      - name: Pull Image from Docker Hub
        run: docker pull maverickgdn01/artifactup-frontend:latest
      - name: Delete Existing Container
        run: docker rm -f artifactup-frontend
      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name artifactup-frontend \
            maverickgdn01/artifactup-frontend:latest